### ISSUE TITLE
populating qualities for adaptive streaming

### ISSUE THREAD

**Issue by munkhbato** [Pong420/videojs-plus#10]
### Description
Hello,
I am trying to populate the quality list for hls. 
I included videojs-contrib-quality-levels plugin and according to the instruction: https://github.com/Pong420/videojs-plus/blob/master/guide/plugins/QualityHls.md 
It should populate itself automatically, right? But it's not working for me. 
How should i connect the quality levels to the QualityMenuItem's entries
https://github.com/Pong420/videojs-plus/blob/master/guide/SettingMenu.md

**Comment by Pong420** [comment]
I have added an [example](https://github.com/Pong420/videojs-plus/blob/master/examples/quality-hls.html)

**Comment by Pong420** [comment]
If you find a warning `plugin videojs-contrib-quality-levels do not exsits` in console.
You may using webpack or others bundler, you should register `videojs-contrib-quality-levels` yourself
```js
import videojs from 'video.js';
import qualityLevels from 'videojs-contrib-quality-levels';
import 'videojs-plus/dist/plugins/quality-hls';

videojs.registerPlugin('qualityLevels', qualityLevels);
```
or assign `videojs` to window before including  `videojs-contrib-quality-levels`
```js
import videojs from 'video.js';
window.videojs = videojs
```

Another possible reason would be your hls format is not correct

**Comment by munkhbato** [comment]
Oh great! Thanks for the example. It's working. I just had to include '../quality-hls/index.js' file.
