### ISSUE TITLE
After resizing the window, Menu back button is invalid

### ISSUE THREAD

**Issue by Ami-OS** [Pong420/videojs-plus#13]
Hello,
After adjusting the window size, the sub-setting menu cannot go back to the main setting menu.
---
### Effect demo video (效果演示影片 28秒): ###
[8-4-2020.mp4 (28s)](https://github.com/Ami-OS/videojs-plus-demo/blob/master/Effect%20demo%20video%20(%E6%95%88%E6%9E%9C%E6%BC%94%E7%A4%BA%E5%BD%B1%E7%89%87)/8-4-2020.mp4?raw=true)
---
### GitHub Pages demo ###
html:
[https://ami-os.github.io/videojs-plus-demo/index.html](https://ami-os.github.io/videojs-plus-demo/index.html)
<br />
file:
[https://github.com/Ami-OS/videojs-plus-demo](https://github.com/Ami-OS/videojs-plus-demo)
---
In fact, this problem also existed half a year ago.
I just remembered.

**Comment by Pong420** [comment]
I have not to focus on this project for a long time. I am afraid this fixed cause another problem. So I publish a pre-release `1.6.0-beta.1`

> In fact, this problem also existed half a year ago.

Haha, this a hobby project the quality is not good.

**Comment by Ami-OS** [comment]
thx, this is work!

> Haha, this a hobby project the quality is not good.

In fact, it is the best open source video player solution I have ever seen.
------
Actually, I still have a functional query,
![19](https://user-images.githubusercontent.com/58389183/78737723-cbcadb00-7982-11ea-91d0-fd8cf630d714.png)
On mobile devices, the HLS quality option in the menu appears to be hidden,
this will make it impossible to switch the resolution manually on the phone

**Comment by Pong420** [comment]
This is Android native browser? have you try chrome ? 
And the video could play normally?

**Comment by Ami-OS** [comment]
Actually I have tested most browsers in google play store,
include:
```
chrome
chrome dev (bate)
firefox for android
Firefox Lite
Firefox for Android Beta
Samsung Internet Browser
Samsung Internet Browser Beta
Opera
Microsoft Edge
Puffin Web Browser
Tor Browser
```
Tested on physical machine
Machine model includes:
```
ROG Phone
IPadPro 1 (第一代)
IPadPro 2 (第二代)
Galaxy Note10+
```
Even if it is switched to "Browse Computer Webpage", Also has no effect.

**Comment by Ami-OS** [comment]
![20](https://user-images.githubusercontent.com/58389183/78742203-f3737080-798d-11ea-9431-d4bb4c885666.PNG)
The phone Chrome console does not output any errors

**Comment by Ami-OS** [comment]
The video can be played correctly

**Comment by Pong420** [comment]
I can reproduce on Safari, most likely these devices or browsers are support HLS natively.
And hence the HLS source will not be parsed by [videojs/videojs-contrib-quality-levels](https://github.com/videojs/videojs-contrib-quality-levels) and I can't render the menu.

You could try to add these options ( for me, not work on safari )

```js
var player = videojs('playerId', {
  html5: {
    hls: {
      overrideNative: true
    },
    nativeAudioTracks: false,
    nativeVideoTracks: false
  }
});
```
reference:
https://github.com/videojs/http-streaming#overridenative

If not work, you may ask for help from videojs developers. 

Also you could create quality menu yourself. See [plugins/Quality.md](https://github.com/Pong420/videojs-plus/blob/master/guide/plugins/Quality.md)

**Comment by Ami-OS** [comment]
Amazing ! this is work !

Works fine on both Android and iOS !
