### ISSUE TITLE
After using the hls plugin, the video speed control button is invalid on Android devices

### ISSUE THREAD

**Issue by Ami-OS** [Pong420/videojs-plus#14]
Hello,

When using the hls plug-in, the movie speed control button is reset, and after selecting the playback speed, the movie speed does not change (only the android device has this problem)

**And this happens only when the hls plugin is used (only the android device has this problem)**

demo video (github does not support large file upload):
[https://www.youtube.com/watch?v=TG6EN_utoCk](https://www.youtube.com/watch?v=TG6EN_utoCk)

This problem can be found in the demo:
[https://pong420.github.io/videojs-plus/examples/quality-hls.html](https://pong420.github.io/videojs-plus/examples/quality-hls.html)

The problem only appears when using the hls plugin (only the android device has this problem):
### Demo
- [x] Base
- [x] Autoplay
- [x] Play List
- [x] Setting Menu
- [x] Subtitles
- [x] Full Window
- [x] Picture in Picture ( Experimental )
- [x] Live (Layout Demo)
- [x] Unload
- [ ] Quality Hls

**Comment by Pong420** [comment]
Just to confirm that the problem is with HLS plugin, speed does not change?
And reset the video time is not related?

**Comment by Ami-OS** [comment]
1. Yes
2. no
------
When I tested it again this morning,
Was it fixed?
thx!

**Comment by Pong420** [comment]
Good, but I do not publish any update.
