### ISSUE TITLE
Main setting menu will not Auto-Responsive

### ISSUE THREAD

**Issue by Ami-OS** [Pong420/videojs-plus#17]
### Main setting menu will not Auto-Responsive

The main menu seems to only initialize the width when the page loads, and main menu width will not automatically change thereafter, sub-menu but will do.

#### The following line have been deleted or overwritten in advance:

> videojs-plus.css::line:1027

```
.vjs-menu .vjs-menu-content .vjs-menu-item.vjs-setting-onoff-item, .vjs-menu .vjs-menu-content .vjs-menu-item.vjs-setting-menu-item {
  width: 16.07143em; }
```

To:

```
.vjs-menu .vjs-menu-content .vjs-menu-item.vjs-setting-onoff-item, .vjs-menu .vjs-menu-content .vjs-menu-item.vjs-setting-menu-item {
  width: 100%; }
```

Test environment setup:

```
const subtitles = [
  {
    default: true,
    kind: 'subtitles',
    srclang: 'zh-TW',
    label: '中文（繁體）中文（繁體）中文（繁體）中文（繁體）',
    src: 'URL/subtitle/TC.txt'
  },
];
player.subtitles().load(subtitles);
```

Result:

![Annotation 2020-07-31 035620](https://user-images.githubusercontent.com/58389183/89028853-f948e500-d2e1-11ea-8060-f055ad0ea6c9.png)

![Annotation 2020-07-31 035710_LI](https://user-images.githubusercontent.com/58389183/89029172-b0456080-d2e2-11ea-934e-4c0db2021e9b.jpg)

But if it is closed during initialization,
environment setup:

```
const subtitles = [
  {
    kind: 'subtitles',
    srclang: 'zh-TW',
    label: '中文（繁體）中文（繁體）中文（繁體）中文（繁體）',
    src: 'URL/subtitle/TC.txt'
  },
];
player.subtitles().load(subtitles);
```

Result:

![Annotation 2020-07-31 040002](https://user-images.githubusercontent.com/58389183/89029205-c2270380-d2e2-11ea-8de6-1e8932895a23.png)

![Annotation 2020-07-31 040048_LI](https://user-images.githubusercontent.com/58389183/89029212-c5ba8a80-d2e2-11ea-986d-eda848f50f9d.jpg)

---

There is another problem. When the menu is in mobile ui mode, if you open the sub-menu and revert to desktop ui mode, the width of the menu is not updated and the menu needs to be triggered again to return to normal.

Result:

![序列 01_1](https://user-images.githubusercontent.com/58389183/89031062-9574eb00-d2e6-11ea-9a83-5d78e9f971f7.gif)

**Comment by Pong420** [comment]
Sorry, i have not idea on this.

**Comment by Ami-OS** [comment]
I use css `width: 100%` to adapt the width, this will solve the above two problems, but this will lose the width transition animation.

like this: https://ami-os.github.io/videojs-plus-demo/index.html?cache=no

But this will not solve the root cause.

**Comment by Pong420** [comment]
I will not do any change until a better solution exists.

**Comment by Ami-OS** [comment]
hi, I noticed `getMenuDimension()`,
this is the behavior of the submenu,
i try to use it in the main menu,
and I found that returning to the main menu seems to call `restore()`

```
_proto.restore = function restore() {
  var dimensions = getMenuDimension(this.player_, this.origin.children);
  this.update(this.origin.children);
  this.resize(dimensions);
};
```

This works very well in the custom menu options

```
    const SettingOnOffItem = videojs.getComponent('SettingOnOffItem');

    class ToggleAnnotation extends SettingOnOffItem {
      constructor(player, options) {
        super(player, {
          ...options, // you must assgin the options
          name: 'ToggleAnnotation', // component name, optional
          label: 'A',
          icon: 'vjs-icon-circle' // videojs icon classname, optional, for small screen
        });

        this.addClass('vjs-setting-annotation');

        // enable by default
        this.update(true);
      }

      /**
       *  @param {Boolean} active
       */
      update(active) {
        super.update(active);

        console.log(this.active);
      }
    }

    videojs.getComponent('SettingMenuButton').prototype.options_.entries.splice(0, 0, 'ToggleAnnotation');
    videojs.registerComponent('ToggleAnnotation', ToggleAnnotation);

    const SettingOptionItem = videojs.getComponent('SettingOptionItem');
    const SettingSubOptionItem = videojs.getComponent('SettingSubOptionItem');
    const authorised = false;

    class QualityMenuItem extends SettingOptionItem {
      constructor(player, options) {
        super(player, {
          ...options, // you must assgin the options
          name: 'QualityMenuItem', // component name, optional
          label: 'Q',
          icon: 'vjs-icon-hd', // videojs icon classname, optional, for small screen
          entries: [
            {
              label: 'HD',
              value: 720
            },
            {
              label: 'SD',
              value: 480,
              default: true
            },
            {
              label: 'Smooth',
              value: 240
            },
            {
              label: 'Auto Auto Auto Auto Auto Auto',
              value: 'Auto'
            }
          ]
        });

        this.addClass('vjs-setting-quality');
      }

      onChange(val) {
        super.onChange(val);
        console.log(val);
      }
    }

    class QualityMenuItemChild extends SettingSubOptionItem {
      handleClick() {
        if (authorised || this.value === 'Auto' || this.value < 720) {
          super.handleClick();
        } else {
          alert('Please Login');
          this.restore();
        }
      }
    }

    videojs.getComponent('SettingMenuButton').prototype.options_.entries.push('QualityMenuItem');
    videojs.registerComponent('QualityMenuItem', QualityMenuItem);
    videojs.registerComponent('QualityMenuItemChild', QualityMenuItemChild);
```

But if it is a non-custom option (e.g. playback-rate),
Will cause EventListener problems:

![序列 01_2](https://user-images.githubusercontent.com/58389183/89726371-c92ecf80-d9ce-11ea-8ce2-4b7b5dc9416d.gif)

The trigger mechanism of the built-in menu options setting items does not seem to be simple?

**Comment by Pong420** [comment]
`playback-rate` is almost the same as the example of custom menu options.
The issue shown on your gif should be you change the width to `100%`.

**Comment by Pong420** [comment]
I have  pushed a new version to
https://github.com/Pong420/videojs-plus/tree/gh-pages/dist

It should fix your first issue, but it may cause other unknown problems. Since`setTimeout` is used

https://github.com/Pong420/videojs-plus/blob/c3451b9188ec373c1fcf03d174c4e3e13dd13e4f/source/Components/SettingMenu/Item/SettingSubOptionItem.js#L24-L29

**Comment by Ami-OS** [comment]
> It should fix your first issue, but it may cause other unknown problems.

yes...

Something wrong with initialization

![序列 01_3](https://user-images.githubusercontent.com/58389183/89730371-d2319800-d9f2-11ea-9b31-fdc57bb548df.gif)

Maybe just me ... https://ami-os.github.io/videojs-plus-demo/index.html

**Comment by Pong420** [comment]
You are right. There are some problems with the built-in menu item.
I have pushed a new version ( include css ) again, hope there is not another bug.
https://github.com/Pong420/videojs-plus/tree/gh-pages/dist

**Comment by Ami-OS** [comment]
worse off ... !?

![序列 01_6](https://user-images.githubusercontent.com/58389183/89751117-ad393580-da83-11ea-9819-d2dcbcc55fba.gif)

https://ami-os.github.io/videojs-plus-demo/index.html

**Comment by Ami-OS** [comment]
The second issue I have thought of a solution, when the window is resized, Turn off the Context Menu or settings menu if it is open

Do the Context Menu and Setting Menu have related API ?

Needs : 

- Whether the Context Menu is on or off [status, e.g. `player.contextMenu()` or `player.contextMenuOpened` Etc., etc]
- Whether the Setting Menu is on or off [status, e.g. `player.settingMenu()`or `player.settingMenuOpened` Etc., etc]
- Close Context Menu [e.g. `player.contextMenu(-1)` Etc., etc]
- Close Setting Menu [e.g. `player.settingMenu(-1)` Etc., etc]

This can also achieve other functions !

(This idea comes from youtube)

**Comment by Pong420** [comment]
Please also update **all** the plugins.

---

For the second issue, I think it is not much important. So I will not implement it by default.
You may add these script yourself
```js
var SettingMenuButton = player.findChild('SettingMenuButton')[0].component;

player.on('playerresize', function () {
  player.ContextMenu.hide();

  if (SettingMenuButton.buttonPressed_) {
    SettingMenuButton.unpressButton();
  }
});
```

For `playerresize` see videojs [ResizeManager](https://docs.videojs.com/resizemanager)

**Comment by Ami-OS** [comment]
Oh, fixds, Thx!
