### ISSUE TITLE
Windows 10 browser compatibility

### ISSUE THREAD

**Issue by Ami-OS** [Pong420/videojs-plus#20]
Hi, Pong420

On Windows Chrome `.vjs-workinghover` Does not load as expected,

### Compare (Use page:https://pong420.github.io/videojs-plus/examples/base.html) :

Windows Google Chrome (`Version 86.0.4240.111 (Official Build) (64-bit)`) :

![2020-10-29_213955](https://user-images.githubusercontent.com/58389183/97583937-6fb8c880-1a32-11eb-876e-678ddf6771fa.png)

Ubuntu Google Chrome (`Version 86.0.4240.111 (Official Build) (64-bit)`) :

![Screenshot from 2020-10-29 21-40-58](https://user-images.githubusercontent.com/58389183/97583015-67ac5900-1a31-11eb-8836-3ddf3cfc3470.png)

**I also tested Mac Google Chrome and it seems that only Windows Google Chrome has problems**

This causes the css that depends on `.vjs-workinghover` to fail to execute as expected.

**Comment by Pong420** [comment]
Hi, please type `videojs.browser.TOUCH_ENABLED` on WIn10 Chrome console. What is the value return?

**Comment by Ami-OS** [comment]
`256`

**Comment by Pong420** [comment]
Please try `1.6.5`.
`vjs-workinghover` is added by videojs if `videojs.browser.IS_IOS` is false.
You may add/remove `vjs-workinghover` yourself if necessary.

**Comment by Ami-OS** [comment]
Oh, I want to ask, what method do you use to hide `vjs-time-tooltip` when touch not enabled ?
Cause it doesn't look like use `vjs-workinghover`
This confuses.

Thx!

**Comment by Pong420** [comment]
By default `vjs-time-tooltip` is display `none`, and show if 
```css
.vjs-workinghover .vjs-progress-control:hover .vjs-mouse-display .vjs-time-tooltip {
    display: block;
}
```

**Comment by Ami-OS** [comment]
On touch enabled `vjs-mouse-display` element Magically disappeared :

![Screenshot from 2020-11-05 18-39-55-edit](https://user-images.githubusercontent.com/58389183/98231051-e0159b80-1f96-11eb-8156-584f2439a25f.jpg)

Is this really by css ?

**Comment by Pong420** [comment]
This is control by `video.js`. See
https://github.com/videojs/video.js/blob/6e7cc75aaa179cfce0819d2f99dac21b9a01b67d/src/js/control-bar/progress-control/seek-bar.js#L467-L470

you could add by yourself
```js
const SeekBar = videojs.getComponent('SeekBar');
if (!SeekBar.prototype.options_.children.includes('mouseTimeDisplay')) {
  SeekBar.prototype.options_.children.splice(1, 0, 'mouseTimeDisplay');
}
```

**Comment by Ami-OS** [comment]
This is exactly what i want. Thx!
