### ISSUE TITLE
Make the setting menu auto resize from the init

### ISSUE THREAD

**Issue by Ami-OS** [Pong420/videojs-plus#21]
Hi, Pong420

https://github.com/Pong420/videojs-plus/blob/3d5d7812ce4f8aaf8f913b9016ce8a5060550609/source/Components/SettingMenu/SettingMenu.js#L22

`offsetWidth` and `offsetHeight` In some browsers, some lengths may be ignored (If zoom).

https://github.com/Pong420/videojs-plus/blob/3d5d7812ce4f8aaf8f913b9016ce8a5060550609/source/Components/SettingMenu/SettingMenu.js#L24

That `mainMenuItems` has been set, why not use `transform` directly.

Like this:

```
videojs-plus/source/Components/SettingMenu/SettingMenu.js

22|    this.mainMenuItems = this.children().slice(0);
23|
24|    this.transform(this.mainMenuItems);
```

**Comment by Pong420** [comment]
>why not use transform directly.

I don't know... probably performance will be better？

Have you try replace `this.resize` with `this.transform`? If this solve your problem, you could send a PR.
https://github.com/Pong420/videojs-plus/blob/3d5d7812ce4f8aaf8f913b9016ce8a5060550609/source/Components/SettingMenu/SettingMenu.js#L26-L29

**Comment by Pong420** [comment]
thanks, `1.6.6` released
