### ISSUE TITLE
Get playback rate range array API requests

### ISSUE THREAD

**Issue by Ami-OS** [Pong420/videojs-plus#23]
Hi,

How (or can) get an array of playback rate ranges?

https://github.com/Pong420/videojs-plus/blob/9ea58563ad9effc92f793edc40016f354dc69a53/source/Components/SettingMenu/PlaybackRate/PlaybackRateSettingItem.js#L11-L22

I tried to use player options, but it didn't work:

<img width="1440" alt="螢幕截圖 2020-11-14 上午11 25 18" src="https://user-images.githubusercontent.com/58389183/99140078-38c0f480-2679-11eb-9cd0-b7062eeef57a.png">

Thx

**Comment by Pong420** [comment]
```js
player.findChild('PlaybackRateSettingItem')[0].component.entries
```
You could suggest other properly api design / submit a PR

**Comment by Ami-OS** [comment]
Currently need to find `PlaybackRateSettingItem` in `children_`

![螢幕擷取畫面 2020-11-15 163140](https://user-images.githubusercontent.com/58389183/99180440-4ea9e480-2761-11eb-86fc-79b00eeaad5c.png)

I think it can be similar to `ContextMenu`

![螢幕擷取畫面 2020-11-15 164000](https://user-images.githubusercontent.com/58389183/99180549-17880300-2762-11eb-8c45-e80cea142a44.png)

Like this:

```javascript
player.SettingMenu.<Item>
```

On issues:

```javascript
player.SettingMenu.PlaybackRateSettingItem.entries
```

---

### On issues, when the array is obtained, the related features can be implemented externally.

#### Get current playback rate (by Videojs) :

```javascript
player.playbackRate()
```

#### Get default playback rate (by Videojs) :

```javascript
player.defaultPlaybackRate()
````

#### Filter the array to keep only what you need :

```javascript
player.findChild('PlaybackRateSettingItem')[0].component.entries.map(t => t.value)
```

Or when the API is implemented :

```javascript
player.SettingMenu.PlaybackRateSettingItem.entries.map(t => t.value)
```

Example out:

![螢幕擷取畫面 2020-11-15 170315](https://user-images.githubusercontent.com/58389183/99180807-7d758a00-2764-11eb-9174-bb18cf5af10c.png)

**Comment by Pong420** [comment]
Please try `1.6.7`

**Comment by Ami-OS** [comment]
This works, thx !
