### ISSUE TITLE
Add more features

### ISSUE THREAD

**Issue by YoussefAhmedus** [Pong420/videojs-plus#24]
Hello,

Great job, could you add fast forward buttons option and keyboard shortcuts and animated actions like pause or play

I hope you do that.

Thanks.

**Comment by Pong420** [comment]
> fast forward buttons

you could refer to `PrevNextButton` in`Playlist` plugin. It is easy to insert a button in to controlbar
https://github.com/Pong420/videojs-plus/blob/master/source/Plugin/Playlist/PrevNextButton.js

> keyboard shortcuts

you could try https://github.com/ctd1500/videojs-hotkeys

> animated actions like pause or play

I have no idea on this

**Comment by YoussefAhmedus** [comment]
Hello,

Thanks for replying, sorry for my late reply
 Animated actions like pause or play like this : https://im4.ezgif.com/tmp/ezgif-4-0e3b7020d7aa.gif
 fast forward buttons I tried to make it but it is not show up I hope you can make it
 keyboard shortcuts I did it thanks 

Thanks

**Comment by Pong420** [comment]
```js
const Button = videojs.getComponent('Button');

class FowardBackwardButton extends Button {
  constructor(player, options) {
    super(player, options);
    this.controlText(options.controlText);
  }

  buildCSSClass() {
    return `${this.options_.className} ${super.buildCSSClass()}`;
  }

  createEl(tag, _, attributes) {
    return super.createEl(
      tag,
      {
        innerHTML: `<span aria-hidden="true" class="vjs-icon-placeholder ${this.options_.icon}"></span>`
      },
      attributes
    );
  }

  handleClick() {
    const type = this.options_.controlText.toLowerCase();
    const player = this.player_;
    const step = 5;
    switch (type) {
      case 'forward':
        return player.currentTime(
          Math.min(player.duration(), player.currentTime() + 5)
        );
      case 'backward':
        return player.currentTime(Math.max(0, player.currentTime() - 5));
        return;
    }
  }
}

videojs.registerComponent('FowardBackwardButton', FowardBackwardButton);

const ControlBar = videojs.getComponent('ControlBar');
const children = ControlBar.prototype.options_.children;
const indexOfPlayToggle = children.indexOf('PlayToggle');

if (indexOfPlayToggle !== -1) {
  children.splice(0, 0, {
    name: 'FowardBackwardButton',
    className: 'vjs-prev-control',
    icon: 'vjs-icon-previous-item',
    controlText: 'Backward'
  });

  children.splice(indexOfPlayToggle + 2, 0, {
    name: 'FowardBackwardButton',
    className: 'vjs-next-control',
    icon: 'vjs-icon-next-item',
    controlText: 'Forward'
  });
}
```

For the icon, you could edit the `createEl` method.

**Comment by Pong420** [comment]
I will not add animated actions.

**Comment by YoussefAhmedus** [comment]
Hello,

Thanks for replying, 

Thanks for fast forward buttons :)

For animated actions I think it will be fantastic if you added it, it will improve appearance of whole player like youtube.

Thanks.

**Comment by Pong420** [comment]
Sorry i am not interested.

FYI, you could implement yourself
https://codepen.io/Hazem/pen/OyZamW

**Comment by YoussefAhmedus** [comment]
Hello,

Thanks for replying,

As you like, any way thanks for your help.

Thanks.
