### ISSUE TITLE
Subtitle Settings

### ISSUE THREAD

**Issue by jhemmmm** [Pong420/videojs-plus#29]
Hello,

Is there any plugins that allow the user to change the subtitle's font/style/etc.

**Comment by Pong420** [comment]
The subtitles elements is children of `.vjs-text-track-display`. You could use css to override its font-family or style

**Comment by jhemmmm** [comment]
> The subtitles elements is children of `.vjs-text-track-display`. You could use css to override its font-family or style

I mean, it's caption settings menu button.

Where did it go?
https://i.imgur.com/ExOR6q1.png

**Comment by Pong420** [comment]
You could try the subtitles plugin 
https://pong420.github.io/videojs-plus/docs/#/./plugins/subtitles

but the  value of `kind` should use `subtitles` instead of `caption`

**Comment by jhemmmm** [comment]
On your documentation, there's no info about setting the subtitle style.
Such as this.
https://i.imgur.com/0wZDMQP.png

Looks like we have to create our own plugin to implement this feature.

**Comment by Pong420** [comment]
You could create it yourself. Take a look at the setting menu document
https://pong420.github.io/videojs-plus/docs/#/./features/setting-menu

if the on-off / optional menu item not suitable for you, you could take a look at   
https://github.com/Pong420/videojs-plus/blob/master/source/Components/SettingMenu/Item/SettingOnOffItem.js
