### ISSUE TITLE
HSL stream Not working on mobile chrome android

### ISSUE THREAD

**Issue by jeremyjohn** [Pong420/videojs-plus#9]
**VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. MediaError {code: 3, message: "The media playback was aborted due to a corruption…media used features your browser did not support."}**

imports:
```
import videojs from 'video.js';
import 'videojs-contrib-hls';
import 'videojs-plus';
import 'videojs-plus/dist/plugins/live';
import 'videojs-plus/dist/plugins/live/style.css';
import 'videojs-plus/dist/videojs-plus.css';
```

Trying to stream an m3u8 file does not work for mobile chrome on android.

Desktop browser works fine.

**Comment by Pong420** [comment]
What is your VideoJS / Android version ?
Also, have you try not to include `videojs-plus` ?

**Comment by jeremyjohn** [comment]
Is it working now, On android chrome it does not send origin header, my server had some CORS requirement.
